[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NODE_VERSION = "18"

# Redirect all requests to Next.js
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/___netlify-handler"
  status = 200

# Handle API routes
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/___netlify-handler"
  status = 200

# Handle auth routes specifically
[[redirects]]
  from = "/api/auth/*"
  to = "/.netlify/functions/___netlify-handler"
  status = 200

# Handle tRPC routes
[[redirects]]
  from = "/api/trpc/*"
  to = "/.netlify/functions/___netlify-handler"
  status = 200
